[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
HUGO_VERSION = "0.110.0"
HUGO_THEME = "repo"
# [[redirects]]
# from = "/"
# to = "/es"
# conditions = { Language = ["es"] }
# force = true
