baseURL = "https://musrenbang.app"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = "CAPSUS - Capital Sustentable"
DefaultContentLanguage = "es"
[Languages.es]
contentDir = "content/spanish"
copyright = "copyright &copy; 2019 [gethugothemes](https://gethugothemes.com) todos los derechos reservados"
home = "Principal"
languageCode = "es-es"
languageName = "Español"
weight = "1"
[Languages.en]
contentDir = "content/english"
copyright = "copyright &copy; 2019 [gethugothemes](https://gethugothemes.com) all right reserved"
home = "Home"
languageCode = "en-us"
languageName = "English"
weight = "2"
[Languages.fr]
contentDir = "content/french"
copyright = "copyright et copie; 2019 [gethugothemes](https://gethugothemes.com) tous droits réservés"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = "2"
[[menu.main]]
URL = "who"
name = "who"
weight = 1
[[menu.main]]
name = "specialties"
weight = 2
URL = "specialties"
hasChildren = true
    [[menu.main]]
    parent = "specialties"
    URL = "specialties/planning-building"
    name = "specialty1"
    [[menu.main]]
    parent = "specialties"
    URL = "specialties/evaluations-studies"
    name = "specialty2"
    [[menu.main]]
    parent = "specialties"
    URL = "specialties/diffusion-development"
    name = "specialty3"
    [[menu.main]]
    parent = "specialties"
    URL = "specialties/public-policies"
    name = "specialty4"
[[menu.main]]
URL = "about"
name = "about"
weight = 3
# [menu.main]]
# URL = "portfolio"
# name = "portfolio"
# weight = 3
[[menu.main]]
URL = "portfolio"
name = "portfolio"
weight = 4
# [[menu.main]]
# URL = "pricing"
# name = "pricing"
# weight = 5
# [[menu.main]]
# URL = "blog"
# name = "blog"
# weight = 6
[[menu.main]]
URL = "contact"
name = "contact"
weight = 5
[[menu.main]]
identifier = "jobs"
URL = "jobs/jobs"
name = "jobs"
weight = 6
[[menu.static]]
URL = "https://themefisher.com/"
name = "Themefisher"
weight = 10
[params]
author = "Themefisher"
description = "Responsive Multipurpose Parallax HTML5 Template"
google_analytics_id = ""
logo = "images/logo.png"
post_share = true
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCstAiOx6maCueeXzIrJYWkEy8HVb2hp0k"
map_latitude = "19.432550"
map_longitude = "-99.209395"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/logo.png"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-dribbble"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
