DefaultContentLanguage = "es"
baseURL = "https://quizzical-bassi-04ccd2.netlify.app/"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = "CAPSUS - Capital Sustentable"
[Languages.en]
contentDir = "content/english"
copyright = "&copy; 2020 CAPSUS S.C., All rights reserved. This website uses [Hugo static pages](https://gohugo.io/). [Template](https://themes.gohugo.io/meghna-hugo/) by [Themefisher](https://themefisher.com/contact/)."
home = "Home"
languageCode = "en-us"
languageName = "Eng"
privacy_notice = "[Privacy Notice](/en/privacy/privacy-notice)"
weight = "2"
[Languages.es]
contentDir = "content/spanish"
copyright = "&copy; 2020 CAPSUS S.C., Todos los derechos reservados. Este sitio web utiliza [Hugo static pages](https://gohugo.io/). [Template](https://themes.gohugo.io/meghna-hugo/) por [Themefisher](https://themefisher.com/contact/)."
home = "Principal"
languageCode = "es-es"
languageName = "Esp"
privacy_notice = "[Aviso de Privacidad](/privacy/privacy-notice)"
weight = "1"
[[menu.main]]
URL = "who"
name = "who"
weight = 1
[[menu.main]]
URL = "expertise"
hasChildren = true
name = "expertise"
weight = 2
[[menu.main]]
URL = "expertise/urban-planning"
name = "expertise1"
parent = "expertise"
[[menu.main]]
URL = "expertise/environmental-studies"
name = "expertise2"
parent = "expertise"
[[menu.main]]
URL = "expertise/dissemination-capacity"
name = "expertise3"
parent = "expertise"
[[menu.main]]
URL = "expertise/public-policies"
name = "expertise4"
parent = "expertise"
[[menu.main]]
URL = "services"
name = "services"
weight = 3
[[menu.main]]
URL = "team"
name = "team"
weight = 4
[[menu.main]]
URL = "careers/careers"
identifier = "careers"
name = "careers"
weight = 5
[[menu.main]]
URL = "contact"
name = "contact"
weight = 6
[[menu.static]]
URL = "https://themefisher.com/"
name = "Themefisher"
weight = 10
[params]
author = "Themefisher"
description = "Responsive Multipurpose Parallax HTML5 Template"
google_analytics_id = "UA-97734727-1"
logo_footer = "images/Footer-Logo-Capsus.png"
logo_footer_eng = "images/LOGO-ENG.png"
logo_nav = "images/Menu-Logo-Capsus.png"
not_found = "images/oops.png"
post_share = true
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCstAiOx6maCueeXzIrJYWkEy8HVb2hp0k"
map_latitude = "19.432550"
map_longitude = "-99.209395"
map_marker = "images/marker-red.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/jquery/jQuery.scrollText.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"
[[params.plugins.js]]
link = "https://kit.fontawesome.com/c3acc1648f.js"
[[params.plugins.js]]
link = "plugins/materialize/js/materialize.min.js"
[params.preloader]
enable = true
preloader = "images/Menu-Logo-Capsus.png"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/capsusmx"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/capitalsustentable"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/capsus-s-c-capital-sustentable-"
